name: Deploy to S3

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    types:
    - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Deploy to S3
      run: |
        aws s3 sync ./ s3://zensimian.com/ --delete --exclude 'node_modules/*'
